### ISSUE TITLE
How to use these icons in XML-Views

### ISSUE THREAD

**Issue by kabachello** [gluons/font-awesome-openui5#1]
How can I use your icons in OpenUI5 XML-Views: e.g. 
`<Button icon="sap-icon://edit" press="onPress" ariaLabelledBy="editButtonLabel"/>`

**Comment by gluons** [comment]
Oh! My doc is incomplete.

Icons are prefixed with `font-awesome`.

You can use `sap-icon://font-awesome/<font awesome icon name>`.

Maybe
```xml
<Button icon="sap-icon://font-awesome/<font awesome icon name>" press="onPress" ariaLabelledBy="editButtonLabel"/>
```

**Comment by kabachello** [comment]
Thanks! Works great!
